# Generated by Django 5.2.8 on 2026-02-01 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMarketingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('channel', models.CharField(max_length=50, verbose_name='Канал')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('os', models.CharField(max_length=20, verbose_name='ОС')),
                ('impressions', models.IntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.IntegerField(default=0, verbose_name='Клики')),
                ('installs', models.IntegerField(default=0, verbose_name='Установки')),
                ('spend', models.FloatField(default=0.0, verbose_name='Затраты ($)')),
                ('iap_revenue', models.FloatField(default=0.0, verbose_name='Доход IAP ($)')),
                ('ad_revenue', models.FloatField(default=0.0, verbose_name='Доход с рекламы ($)')),
                ('retention_d1', models.FloatField(default=0.0, verbose_name='Retention D1 (%)')),
                ('retention_d7', models.FloatField(default=0.0, verbose_name='Retention D7 (%)')),
                ('retention_d30', models.FloatField(default=0.0, verbose_name='Retention D30 (%)')),
                ('m01', models.FloatField(default=0.0, verbose_name='ARPU')),
                ('m02', models.FloatField(default=0.0, verbose_name='ARPPU')),
                ('m03', models.FloatField(default=0.0, verbose_name='ROAS')),
                ('m04', models.FloatField(default=0.0, verbose_name='ROI')),
                ('m05', models.FloatField(default=0.0, verbose_name='LTV')),
                ('m06', models.FloatField(default=0.0, verbose_name='CPI')),
                ('m07', models.FloatField(default=0.0, verbose_name='CTR')),
                ('m08', models.FloatField(default=0.0, verbose_name='CR (Install)')),
                ('m09', models.FloatField(default=0.0, verbose_name='CPA')),
                ('m10', models.FloatField(default=0.0, verbose_name='eCPM')),
                ('f11', models.FloatField(default=0.0, verbose_name='Factor 11')),
                ('f12', models.FloatField(default=0.0, verbose_name='Factor 12')),
                ('f13', models.FloatField(default=0.0, verbose_name='Factor 13')),
                ('f14', models.FloatField(default=0.0, verbose_name='Factor 14')),
                ('f15', models.FloatField(default=0.0, verbose_name='Factor 15')),
                ('f16', models.FloatField(default=0.0, verbose_name='Factor 16')),
                ('f17', models.FloatField(default=0.0, verbose_name='Factor 17')),
                ('f18', models.FloatField(default=0.0, verbose_name='Factor 18')),
                ('f19', models.FloatField(default=0.0, verbose_name='Factor 19')),
                ('f20', models.FloatField(default=0.0, verbose_name='Factor 20')),
                ('f21', models.FloatField(default=0.0, verbose_name='Factor 21')),
                ('f22', models.FloatField(default=0.0, verbose_name='Factor 22')),
                ('f23', models.FloatField(default=0.0, verbose_name='Factor 23')),
                ('f24', models.FloatField(default=0.0, verbose_name='Factor 24')),
                ('f25', models.FloatField(default=0.0, verbose_name='Factor 25')),
                ('f26', models.FloatField(default=0.0, verbose_name='Factor 26')),
                ('f27', models.FloatField(default=0.0, verbose_name='Factor 27')),
                ('f28', models.FloatField(default=0.0, verbose_name='Factor 28')),
                ('f29', models.FloatField(default=0.0, verbose_name='Factor 29')),
                ('f30', models.FloatField(default=0.0, verbose_name='Factor 30')),
                ('f31', models.FloatField(default=0.0, verbose_name='Factor 31')),
                ('f32', models.FloatField(default=0.0, verbose_name='Factor 32')),
                ('f33', models.FloatField(default=0.0, verbose_name='Factor 33')),
                ('f34', models.FloatField(default=0.0, verbose_name='Factor 34')),
                ('f35', models.FloatField(default=0.0, verbose_name='Factor 35')),
                ('f36', models.FloatField(default=0.0, verbose_name='Factor 36')),
                ('f37', models.FloatField(default=0.0, verbose_name='Factor 37')),
                ('f38', models.FloatField(default=0.0, verbose_name='Factor 38')),
                ('f39', models.FloatField(default=0.0, verbose_name='Factor 39')),
                ('f40', models.FloatField(default=0.0, verbose_name='Factor 40')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Маркетинговые данные',
                'verbose_name_plural': 'Маркетинговые данные',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Имя и Фамилия')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('website', models.URLField(blank=True, verbose_name='Сайт проекта')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Индустрия')),
                ('timezone', models.CharField(default='Moscow Time (UTC+3)', max_length=100, verbose_name='Часовой пояс')),
                ('subscription_plan', models.CharField(choices=[('Free', 'Free'), ('Indie', 'Indie'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], default='Free', max_length=20, verbose_name='Тариф')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
