# Generated by Django 5.2.9 on 2026-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_gamemarketingdata_f11_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemarketingdata',
            name='ad_revenue',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Доход с рекламы ($)'),
        ),
        migrations.AlterField(
            model_name='gamemarketingdata',
            name='iap_revenue',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Доход IAP ($)'),
        ),
        migrations.AlterField(
            model_name='gamemarketingdata',
            name='spend',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Затраты ($)'),
        ),
    ]
